apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservergolang
spec:
  replicas: 1

  selector:
    matchLabels:
      app: webservergolang

  template:
    metadata:
      labels:
        app: webservergolang
    spec:
      containers:
        - image: img-webserver_golang
          name: webservergolang

---

apiVersion: v1
kind: Service
metadata:
  name: webservergolang-service
  labels:
    app: webservergolang-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: webservergolang